version: 2.1

jobs:
   build:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: https://rdurlo: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@github.com/rdurlo/CxCLIScript.git
      - run: ls -l

      


